#!/usr/bin/perl
# http://czyborra.com/unifont/braille.pl
# 1998-10-30 all wrong from czyborra@cs.tu-berlin.de
# 2003-02-15 correction hint from dominique@unruh.de
# see http://www.egroups.com/group/gnu-unifont/

for ($c = 0; $c < 256; ++ $c)
{


    printf (

	     "28%02X:000000%d%d%d%d00%d%d%d%d00%d%d%d%d00%d%d%d%d0000\n", 
	     
	     $c, 

	     $c & 1 ? 3 : 2, $c & 8 ? 6 : 2,
	     $c & 1 ? 3 : 0, $c & 8 ? 6 : 0,

	     $c & 2 ? 3 : 2, $c & 16 ? 6 : 2,
	     $c & 2 ? 3 : 0, $c & 16 ? 6 : 0,

	     $c & 4 ? 3 : 2, $c & 32 ? 6 : 2,
	     $c & 4 ? 3 : 0, $c & 32 ? 6 : 0,

	     $c & 64 ? 3 : 2, $c & 128 ? 6 : 2,
	     $c & 64 ? 3 : 0, $c & 128 ? 6 : 0

	     );
}
