.TH HEXMERGE 1 "2008 Jul 06"
.SH NAME
hexmerge \- Merge two or more GNU Unifont .hex font files into one.
.SH SYNOPSIS
.br
.B hexmerge input_font1.hex input_font2.hex > output_font.bdf
.SH DESCRIPTION
.B hexmerge
reads two or more GNU Unifont .hex file, sorts them, and writes
the combined font to stdout.
.PP
.SH FILES
.TP 15
*.hex GNU Unifont font files
.SH SEE ALSO
.BR bdfimplode (1),
.BR hex2bdf (1),
.BR hex2bdf-split (1),
.BR hex2sfd (1),
.BR hexbraille (1),
.BR hexdraw (1),
.BR johab2ucs2 (1),
.BR unibmp2hex (1),
.BR unicoverage (1),
.BR unidup (1),
.BR unihex2bmp (1),
.BR unipagecount (1),
.BR uniunmask (1)
.SH AUTHOR
.B hexmerge
was written by Roman Czyborra.
.SH LICENSE
.B hexmerge
is Copyright \(co 1998 Roman Czyborra, and is released under the following
terms (taken from http://czyborra.com):
.PP
"All of my works you find here are freeware. You may freely copy, use, quote,
modify or redistribute them as long as you properly attribute my contribution
and have given a quick thought about whether Roman might perhaps be interested
to read what you did with his stuff. Horizontal rules don't apply."
.SH BUGS
No known bugs exist.
